Controllers/CDRController.cs
using HyAdmin.AppUtilities;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HyAdmin.Controllers
{
    public class CDRController : Controller
    {
        // GET: CDR
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UploadCSV()
        {
            return View();
        }

        public ActionResult ManageCDR()
        {
            return View();
        }

        public ActionResult Reports()
        {
            return View();
        }

        public ActionResult CDRMembers()
        {
            return View();
        }

        public ActionResult FlaggedItems()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadCDREntry(string __RequestVerificationToken)
        {
            Token t = new Token();
            t = t.GetToken("");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.UploadCDREntry;

            var client = new RestClient($"{baseURL}{endpoint}");
            var request = new RestRequest(Method.POST);
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            request.AddParameter("application/x-www-form-urlencoded", ParameterType.RequestBody);
            IRestResponse response = client.Execute(request);
            return Json(response.Content, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCDRProcedures(string __RequestVerificationToken)
        {
            Token t = new Token();
            t = t.GetToken("");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.AddCDRProcedures;

            var client = new RestClient($"{baseURL}{endpoint}");
            var request = new RestRequest(Method.POST);
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            request.AddParameter("application/x-www-form-urlencoded", ParameterType.RequestBody);
            IRestResponse response = client.Execute(request);
            return Json(response.Content, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCDRProviders(string __RequestVerificationToken)
        {
            Token t = new Token();
            t = t.GetToken("");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.AddCDRProviders;

            var client = new RestClient($"{baseURL}{endpoint}");
            var request = new RestRequest(Method.POST);
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            request.AddParameter("application/x-www-form-urlencoded", ParameterType.RequestBody);
            IRestResponse response = client.Execute(request);
            return Json(response.Content, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AssignCDRProcedures(string LegacyCode, int DependantId, string ProcedureCode, string __RequestVerificationToken)
        {
            Token t = new Token();
            t = t.GetToken("");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.AssignCDRProcedures;
            var client = new RestClient($"{baseURL}{endpoint}/{LegacyCode}/{DependantId}/{ProcedureCode}");
            var request = new RestRequest(Method.POST);
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            request.AddParameter("application/x-www-form-urlencoded", $"LegacyCode={LegacyCode}&DependantId={DependantId}&ProcedureCode={ProcedureCode}", ParameterType.RequestBody);
            IRestResponse response = client.Execute(request);
            return Json(response.Content, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AssignCDRProviders(string LegacyCode, int DependantId, int ProviderId, string __RequestVerificationToken)
        {
            Token t = new Token();
            t = t.GetToken("");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.AssignCDRProviders;

            var client = new RestClient($"{baseURL}{endpoint}/{LegacyCode}/{DependantId}/{ProviderId}");
            var request = new RestRequest(Method.POST);
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            request.AddParameter("application/x-www-form-urlencoded", $"LegacyCode={LegacyCode}&DependantId={DependantId}&Procedure={ProviderId}", ParameterType.RequestBody);
            IRestResponse response = client.Execute(request);
            return Json(response.Content, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/CDR/CDRMembers.cshtml
@{
    ViewBag.Title = "CDRMembers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="~/Content/files/bower_components/datatables.net-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" type="text/css" href="~/Content/files/assets/pages/data-table/css/buttons.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="~/Content/files/bower_components/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css">

<!-- [ breadcrumb ] start -->
<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">
                    <h4 class="m-b-10">CDR</h4>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="@Url.Action("Index", "Home")">
                            <i class="feather icon-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Members</a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
</div>
<!-- [ breadcrumb ] end -->

<div class="pcoded-inner-content">
    <div class="main-body">
        <div class="page-wrapper">
            <!-- Page-body start -->
            <div class="page-body">
                <div class="row">
                    <div class="col-sm-8">
                        <div class="card">
                            <div class="card-header">
                                <h5>View CDR Member</h5>
                            </div>
                            <div class="card-block">
                                <div id="list-of-cdr-members">
                                    <table id="view-cdr-members-table" style="width:100%; font-size:12px;" class="table table-striped table-bordered nowrap">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>EnrolleeNo</th>
                                                <th>Group</th>
                                                <th>Email</th>
                                                <th>Phone</th>
                                                <th>LastRefilDate</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Hygeia</td>
                                                <td>112</td>
                                                <td>HMO</td>
                                                <td>aa@gmail.com</td>
                                                <td>123456789</td>
                                                <td>19th February</td>
                                                <td><button id='btnView' class='btn btn-primary btn-sm' type='button' onclick="showProvider()">View</button></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div id="show-member-history" style="display:none">
                            <div class="card" style="height:400px;">
                                <div class="card-header">
                                    <h5>History</h5>
                                </div>
                                <div class="card-body p-b-0">

                                </div>
                            </div>

                        </div>

                    </div>
                    <div class="col-sm-4" id="show-providers" style="display:none;">

                        <div class="card" style="height:500px">
                            <div class="card-header">
                                <h5>Providers</h5>
                            </div>
                            <div class="card-body p-b-0">


                            </div>
                        </div>
                        <div class="card" style="height:500px;">
                            <div class="card-header">
                                <h5>Procedures</h5>
                            </div>
                            <div class="card-body p-b-0">

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts{

    <!-- data-table js -->
    <script src="~/Content/files/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/Content/files/assets/pages/data-table/js/jszip.min.js"></script>
    <script src="~/Content/files/assets/pages/data-table/js/pdfmake.min.js"></script>
    <script src="~/Content/files/assets/pages/data-table/js/vfs_fonts.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>

    <script src="~/Content/files/assets/pages/data-table/extensions/row-reorder/js/row-reorder-custom.js"></script>
    <script>

        //$('#btnView').click(function (e) {
        //    e.preventDefault();
        //    showProvider();
        //})
        
            $('#view-cdr-members-table').DataTable();
    
        var showProvider = function () {
            $('#show-providers').show();
            $('#show-member-history').show();
            $('#show-member-procedures').show();

        };
    </script>
}

Views/CDR/FlaggedItems.cshtml
@{
    ViewBag.Title = "FlaggedItems";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="~/Content/files/bower_components/datatables.net-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" type="text/css" href="~/Content/files/assets/pages/data-table/css/buttons.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="~/Content/files/bower_components/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css">


<!-- [ breadcrumb ] start -->
<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">
                    <h4 class="m-b-10">CDR</h4>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="@Url.Action("Index", "Home")">
                            <i class="feather icon-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Flagged Items</a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
</div>
<!-- [ breadcrumb ] end -->

<div class="pcoded-inner-content">
    <div class="main-body">
        <div class="page-wrapper">
            <!-- Page-body start -->
            <div class="page-body">
                <div class="card table-card">
                    <div class="card-header">
                        <h4>Flagged Items</h4>
                    </div>
                    <div class="card-body p-b-0" style="padding: 30px;overflow-x: auto;">

                        <div class="dt-responsive table-responsive" id="flagged-items-list">
                            <table id="flag-items-table" class="table table-striped table-bordered nowrap">
                                <thead>
                                    <tr>
                                        <th>EnrolleeNo</th>
                                        <th>Name</th>
                                        <th>GroupName</th>
                                        <th>ProviderName</th>
                                        <th>ProcedureCode</th>
                                        <th>Qty</th>
                                        <th>ProcedureDesc</th>
                                        <th>Email</th>
                                        <th>Phone</th>
                                        <th>Region</th>
                                        <th>Register</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>12</td>
                                        <td>12</td>
                                        <td>12</td>
                                        <td>12</td>
                                        <td>12</td>
                                        <td>12</td>
                                        <td>12</td>
                                        <td>12</td>
                                        <td>12</td>
                                        <td>12</td>
                                        <td><button class='btn btn-primary btn-sm'><i class='fa fa-check'></i></button></td>
                                        <td><button class='btn btn-danger btn-sm'><i class='fa fa-trash'></i></button></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <!-- data-table js -->
    <script src="~/Content/files/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/Content/files/assets/pages/data-table/js/jszip.min.js"></script>
    <script src="~/Content/files/assets/pages/data-table/js/pdfmake.min.js"></script>
    <script src="~/Content/files/assets/pages/data-table/js/vfs_fonts.js"></script>
    @*<script src="~/Content/files/assets/pages/data-table/extensions/row-reorder/js/dataTables.rowReorder.min.js"></script>*@
    <script src="~/Content/files/bower_components/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>

    <script src="~/Content/files/assets/pages/data-table/extensions/row-reorder/js/row-reorder-custom.js"></script>


    <script>
        $('#flag-items-table').DataTable();
    </script>
    
}

Views/CDR/UploadCSV.cshtml
@{
    ViewBag.Title = "UploadCSV";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" type="text/css" href="~/Content/files/bower_components/datatables.net-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" type="text/css" href="~/Content/files/assets/pages/data-table/css/buttons.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="~/Content/files/bower_components/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css">

<!-- [ breadcrumb ] start -->
<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">
                    <h4 class="m-b-10">CDR</h4>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="@Url.Action("Index", "Home")">
                            <i class="feather icon-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Upload</a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
</div>
<!-- [ breadcrumb ] end -->

<div class="pcoded-inner-content">
    <div class="main-body">
        <div class="page-wrapper">
            <!-- Page-body start -->
            <div class="page-body">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="card">
                            <div class="card-header">
                                <h5>Upload CDR File</h5>
                            </div>
                            <div class="card-body p-b-0">
                                <h6>Upload CSV File</h6>
                                <div style="background: whitesmoke;padding: 13px;border: 1px solid #CCC;">
                                    <input id="file-name" type="file" />
                                    <button id="btnUpload" style="float:right" class="btn btn-primary btn-sm" type="submit">Upload <i class="fa fa-upload"></i></button>
                                </div>
                                <h5 style="padding-top:14px;"><a href="#">Sample CSV Upload File</a></h5>
                                <div id="sample-upload" style="padding-top:25px">
                                    <table id="sample-cdr-upload-table" class="table table-striped table-bordered nowrap">
                                        <thead>
                                            <tr>
                                                <th>EnrolleeNumber</th>
                                                <th>DependantId</th>
                                                <th>ProcedureCode</th>
                                                <th>ProviderId</th>
                                                <th>Qty</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>1</td>
                                                <td>2</td>
                                                <td>3</td>
                                                <td>4</td>
                                                <td>5</td>
                                            </tr>
                                            <tr>
                                                <td>1</td>
                                                <td>2</td>
                                                <td>3</td>
                                                <td>4</td>
                                                <td>5</td>
                                            </tr>
                                            <tr>
                                                <td>1</td>
                                                <td>2</td>
                                                <td>3</td>
                                                <td>4</td>
                                                <td>5</td>
                                            </tr>
                                            <tr>
                                                <td>1</td>
                                                <td>2</td>
                                                <td>3</td>
                                                <td>4</td>
                                                <td>5</td>
                                            </tr>
                                            <tr>
                                                <td>1</td>
                                                <td>2</td>
                                                <td>3</td>
                                                <td>4</td>
                                                <td>5</td>
                                            </tr>
                                            <tr>
                                                <td>1</td>
                                                <td>2</td>
                                                <td>3</td>
                                                <td>4</td>
                                                <td>5</td>
                                            </tr>
                                            <tr>
                                                <td>1</td>
                                                <td>2</td>
                                                <td>3</td>
                                                <td>4</td>
                                                <td>5</td>
                                            </tr>
                                            <tr>
                                                <td>1</td>
                                                <td>2</td>
                                                <td>3</td>
                                                <td>4</td>
                                                <td>5</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6">

                        <div class="card table-card" id="display-cdr-table-card" style="height: 720px;">
                            <div class="card-body p-b-0">

                                <h5 id="upload-preview" style="text-align:center; margin-top:300px">Upload to Preview</h5>
                                <div id="show-cdr-upload" style="display:none">
                                    <table class="table table-striped" id="csv-table" style="width:100%">
                                        <thead>
                                            <tr>
                                                <th>EnrolleeNumber</th>
                                                <th>DependantId</th>
                                                <th>ProcedureCode</th>
                                                <th>ProviderId</th>
                                                <th>Qty</th>
                                            </tr>
                                        </thead>
                                        <tbody id="upload-body">
                                            
                                        </tbody>
                                    </table>
                                </div>
                                <div id="button-visibility" style="margin-right:10px; padding-top:12px; float:right; display:none">
                                    <button id="btn-submit-uploaded-cdr-file" type="submit" class="btn btn-success btn-sm">Save <i class="fa fa-upload"></i></button>
                                </div>
                            </div>
                        </div>



                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<a href="#" id="post-cdr-uploads" data-url="@Url.Action("UploadCDREntry", "CDR")"></a>

@section scripts{


    <!-- data-table js -->
    <script src="~/Content/files/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/Content/files/assets/pages/data-table/js/jszip.min.js"></script>
    <script src="~/Content/files/assets/pages/data-table/js/pdfmake.min.js"></script>
    <script src="~/Content/files/assets/pages/data-table/js/vfs_fonts.js"></script>
    <script src="~/Content/files/assets/pages/data-table/extensions/row-reorder/js/dataTables.rowReorder.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>

    <script src="~/Content/files/assets/pages/data-table/extensions/row-reorder/js/row-reorder-custom.js"></script>


    <script>
        var uploadDataArray = [];

        $('#btnUpload').click(function (e) {
            e.preventDefault();

            var regex = /^([a-zA-Z0-9\s_\\.\-:])+(.csv)$/;
            if (regex.test($("#file-name").val().toLowerCase())) {
                $('#show-cdr-upload').show();
                //$('#empty-content-upload').css("margin-top", "50px");
                $('#upload-preview').hide();

                var rdr = new FileReader();
                rdr.onload = function (e) {
                    var theRows = e.target.result.split("\n");
                    var newRow = "";
                    for (var row = 0; row < theRows.length; row++) {

                        var columns = theRows[row].split(",");
                        newRow += "<tr><td>" + columns[0] + "</td><td>" + columns[1] + "</td><td>" + columns[2] + "</td><td>" + columns[3] + "</td><td>" + columns[4] + "</td></tr>";

                        uploadDataArray.push({
                            enrolleeNo: columns[0],
                            dependantId: columns[1],
                            procedureCode: columns[2],
                            providerId: columns[3],
                            qty: columns[4]
                        });
                    }

                    $('#csv-table').append(newRow);
                    $('#csv-table').DataTable();
                    $('#button-visibility').show();
                }

                rdr.readAsText($("#file-name")[0].files[0]);
            }
            else {
                alert("Please upload a valid CSV file.");

            }

        });

        var saveToDb = function (index) {
            if (index === uploadDataArray.length) {
                alert('Processing complete');
                return false;
            }

            var postCdrUploadsURL = $('#post-cdr-uploads').data('url');
            $.ajax({
                url: postCdrUploadsURL,
                type: "POST",
                data: uploadDataArray[index],
                contentType: 'application/json; charset=utf-8',
                success: function (data) {
                    console.log(data);
                    saveToDb(++index);
                },
                error: function (msg) { console.log(msg); }
            });
           
        }


        $('#btn-submit-uploaded-cdr-file').click(function (e) {
            e.preventDefault();
            saveToDb(0);
        })
    </script>
}