Controllers/TimePeriodController.cs
using HyAdmin.AppUtilities;
using HyDirect.Filters;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HyAdmin.Controllers
{
    [MaintenanceFilter]
    [Authorize(Roles = "Admin,MerchantAdmin,Staff")]
    public class TimePeriodController : Controller
    {
        // GET: TPSManagement
        public ActionResult Index()
        {
            // This should be the dashboard containing statistics
            // -- No of subscriptions, subscription rates, Turn Over/Conversion rate, Average Monthly Registrations,
            // -- Total enrollees registered, Total enrolleess suspended, termination, total pending renewals (Cost, Count)
            // There should be moratorium on these group of plans
            return View();
        }
        
        public ActionResult SetupBenefits()
        {
            return View();
        }

        public ActionResult SetupMonetaryLimits()
        {
            return View();
        }
        
        public ActionResult Requests()
        {
            return View();
        }

        public ActionResult RetailGraduatedPlanTPeriods()
        {
            Token t = new Token();
            t = t.GetToken("admin");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.RetailGraduatedPlanTPeriods;

            var client = new RestClient($"{baseURL}{endpoint}");
            var request = new RestRequest(Method.GET);
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("content-type", "application/x-www-form-urlencoded");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            IRestResponse response = client.Execute(request);

            return Json(new { Success = (response.IsSuccessful), Result = response.Content }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult PlanBenefits(int id)
        {
            Token t = new Token();
            t = t.GetToken("admin");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.PlanBenefits;

            var client = new RestClient($"{baseURL}{endpoint}/{id}");
            var request = new RestRequest(Method.GET);
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("content-type", "application/x-www-form-urlencoded");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            IRestResponse response = client.Execute(request);

            return Json(new { Success = (response.IsSuccessful), Result = response.Content }, JsonRequestBehavior.AllowGet);
        }

        [Route("TimePeriod/BenefitProcedures/{benefitCodeId}/{planId}/{timePeriodId}")]
        public ActionResult BenefitProcedures(int benefitCodeId, int planId, int timePeriodId)
        {
            Token t = new Token();
            t = t.GetToken("admin");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.BenefitProcedures;

            var client = new RestClient($"{baseURL}{endpoint}/{benefitCodeId}/{planId}/{timePeriodId}");
            var request = new RestRequest(Method.GET);
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("content-type", "application/x-www-form-urlencoded");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            IRestResponse response = client.Execute(request);

            return Json(new { Success = (response.IsSuccessful), Result = response.Content }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult BenefitLookUp(int benefitCodeId)
        {
            Token t = new Token();
            t = t.GetToken("admin");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.BenefitLookUp;

            var client = new RestClient($"{baseURL}{endpoint}/{benefitCodeId}");
            var request = new RestRequest(Method.GET);
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("content-type", "application/x-www-form-urlencoded");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            IRestResponse response = client.Execute(request);

            return Json(new { Success = (response.IsSuccessful), Result = response.Content }, JsonRequestBehavior.AllowGet);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Respond(string __RequestVerificationToken, int id, string category, bool isApproved, string comments)
        {
            Token t = new Token();
            t = t.GetToken("admin");
            string baseURL = APIServices.BaseURL;

            string endpoint = "";
            string adjuster = User.Identity.Name.Replace("@hygeiahmo.com", "");

            switch (category)
            {
                case "Activation Requests":
                    endpoint = APIServices.TPSRegistration;
                    break;
                case "Re-Activation Requests":
                    endpoint = APIServices.TPSReActivation;
                    break;
                case "Suspension Requests":
                    endpoint = APIServices.TPSSusension;
                    break;
                case "Termination Requests":
                    endpoint = APIServices.TPSTermination;
                    break;
            }

            var request = new RestRequest(Method.POST);
            var client = new RestClient($"{baseURL}{endpoint}");
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("content-type", "application/x-www-form-urlencoded");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            request.AddParameter("application/x-www-form-urlencoded", $"Id={id}&Comments={comments}&Adjuster={adjuster}&Response={isApproved}", ParameterType.RequestBody);
            IRestResponse response = client.Execute(request);
            return Json(new { Success = (response.IsSuccessful), Result = response.Content }, JsonRequestBehavior.AllowGet);
            
        }


        //[Route("TimePeriod/ProcedureSetup/{benefitCodeId}/{planId}/{timePeriodId}/{status}/{procedurecode}")]
        public ActionResult ProcedureSetup(int benefitCodeId, int planId, int timePeriodId, bool status, string procedurecode)
        {
            Token t = new Token();
            t = t.GetToken("admin");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.ProcedureSetup;

            string Adjuster = User.Identity.Name;
            var client = new RestClient($"{baseURL}{endpoint}/{benefitCodeId}/{planId}/{timePeriodId}/{status}/{Adjuster}/{procedurecode}");
            var request = new RestRequest(Method.GET);
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("content-type", "application/x-www-form-urlencoded");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            IRestResponse response = client.Execute(request);

            return Json(new { Success = (response.IsSuccessful), Result = response.Content }, JsonRequestBehavior.AllowGet);
        }
        




        [Route("TimePeriod/GetTimeMonetaryLimits/{planId}/{timePeriodId}")]
        public ActionResult GetTimeMonetaryLimits(int planId, int timePeriodId)
        {
            Token t = new Token();
            t = t.GetToken("admin");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.GetTimeMonetaryLimits;

            var client = new RestClient($"{baseURL}{endpoint}/{planId}/{timePeriodId}");
            var request = new RestRequest(Method.GET);
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("content-type", "application/x-www-form-urlencoded");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            IRestResponse response = client.Execute(request);

            return Json(new { Success = (response.IsSuccessful), Result = response.Content }, JsonRequestBehavior.AllowGet);
        }

        [Route("TimePeriod/SaveTimeMonetaryLimits/{planId}/{timePeriodId}/{amount}")]
        public ActionResult SaveTimeMonetaryLimits(int planId, int timePeriodId, double amount)
        {
            Token t = new Token();
            t = t.GetToken("admin");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.SaveTimeMonetaryLimits;
            string adjuster = User.Identity.Name.Replace("@hygeiahmo.com", "");

            var client = new RestClient($"{baseURL}{endpoint}/{planId}/{timePeriodId}/{amount}/{adjuster}");
            var request = new RestRequest(Method.POST);
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("content-type", "application/x-www-form-urlencoded");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            IRestResponse response = client.Execute(request);

            return Json(new { Success = (response.IsSuccessful), Result = response.Content }, JsonRequestBehavior.AllowGet);
        }

        [Route("TimePeriod/UpdateTimeMonetaryLimits/{id}/{status}")]
        public ActionResult UpdateTimeMonetaryLimits(int id, bool status)
        {
            Token t = new Token();
            t = t.GetToken("admin");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.UpdateTimeMonetaryLimits;

            var client = new RestClient($"{baseURL}{endpoint}/{id}/{status}");
            var request = new RestRequest(Method.POST);
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("content-type", "application/x-www-form-urlencoded");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            IRestResponse response = client.Execute(request);

Views/TimePeriod/SetupMonetaryLimits.cshtml
@{
    ViewBag.Title = "Time Periods";
}

<!-- Switch component css -->
<link rel="stylesheet" type="text/css" href="~/Content/files/bower_components/switchery/css/switchery.min.css">

<!-- [ breadcrumb ] start -->
<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">
                    <h4 class="m-b-10">Retail Products</h4>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="@Url.Action("Index", "Home")">
                            <i class="feather icon-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Time Period</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Setup Graduated Limits</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- [ breadcrumb ] end -->

<style>
    .pull-right {
        float: right !important;
    }

    .empty-notification {
        padding: 42px;
        font-weight: lighter;
        font-size: 34px;
    }

    .card .card-block .dropdown-menu > a {
        padding: 4px 7px;
        line-height: 1.429;
    }

    .link-text {
        cursor: pointer;
        font-weight: 600;
        font-size: 12px;
    }

    #category_data tr td {
        padding-bottom: 11px !important;
    }
    select {
        margin-top: 4px;
        font-size: 14px !important;
        color: #000 !important;
    }
</style>

<div class="pcoded-inner-content">
    <div class="main-body">
        <div class="page-wrapper">
            <!-- Page-body start -->
            <div class="page-body">

                <div class="row">
                    <div class="col-lg-6">
                        <div class="card recent-operations-card">
                            <div class="card-header">
                                <h5 id="category_name">Setup Plan, Time Period, Limits</h5>
                            </div>
                            <div class="card-block">
                                <div class="card-scroll">
                                    <form class="form-material">
                                        <div class="row">
                                            <div class="col-sm-3">
                                                <div class="form-group form-primary">
                                                    <select id="plans" class="form-control" onchange="GetTimeMonetaryLimits()">
                                                        <option value="-1">Plan</option>
                                                    </select>
                                                    <span class="form-bar"></span>
                                                </div>

                                            </div>

                                            <div class="col-sm-3">
                                                <div class="form-group form-primary">
                                                    <select id="time_periods" class="form-control" onchange="GetTimeMonetaryLimits()">
                                                        <option value="-1">Time Period</option>
                                                    </select>
                                                    <span class="form-bar"></span>
                                                </div>
                                            </div>

                                            <div class="col-sm-3">
                                                <div class="form-group form-primary">
                                                    <input type="number" name="Amount" id="Amount" class="form-control" required="">
                                                    <span class="form-bar"></span>
                                                    <label class="float-label">Amount</label>
                                                </div>
                                            </div>

                                            <div class="col-sm-3">
                                                <a class="btn btn-small btn-primary" style="color: #FFF;" onclick="Save()">Save&nbsp;<i class="fa fa-save"></i></a>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="card recent-operations-card">
                            <div class="card-header">
                                <h5 id="PlanName">Existing Setup</h5>
                            </div>
                            <div class="card-block">
                                <div class="card-scroll">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <table id="money_limits" class="table table-borderless table-striped">
                                                <thead>
                                                    <tr>
                                                        <th>Time Period</th>
                                                        <th>Amount</th>
                                                        <th>
                                                            &nbsp;
                                                        </th>
                                                    </tr>
                                                </thead>
                                                <tbody id=""></tbody>
                                                <tfoot>
                                                    <tr>
                                                        <th>Time Period</th>
                                                        <th>Amount</th>
                                                        <th>
                                                            &nbsp;
                                                        </th>
                                                    </tr>
                                                </tfoot>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <a id="GPTPURL" class="hide" data-url="@Url.Action("RetailGraduatedPlanTPeriods", "TimePeriod")"></a>
    <a id="dataURL" class="hide" data-url="@Url.Action("GetTimeMonetaryLimits", "TimePeriod")"></a>
    <a id="SMTLURL" class="hide" data-url="@Url.Action("SaveTimeMonetaryLimits", "TimePeriod")"></a>
    <a id="UMTLURL" class="hide" data-url="@Url.Action("UpdateTimeMonetaryLimits", "TimePeriod")"></a>

    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "formUrl" }))
    {
        @Html.AntiForgeryToken()
    }
</div>


@section scripts{

    <!-- Switch component js -->
    <script src="~/Content/files/bower_components/switchery/js/switchery.min.js"></script>
    <!-- data-table js -->
    <script src="~/Content/files/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    @*<script src="~/Content/files/assets/pages/data-table/js/jszip.min.js"></script>
        <script src="~/Content/files/assets/pages/data-table/js/pdfmake.min.js"></script>
        <script src="~/Content/files/assets/pages/data-table/js/vfs_fonts.js"></script>*@
    <script src="~/Content/files/bower_components/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            var dataURL = $('#GPTPURL').data('url');
            $.getJSON(dataURL, function (data) {
                data = $.parseJSON(data.Result);

                FormatPlan(data.plans);
                FormatTimePeriod(data.timePeriods);
            });
        });
        function GetTimeMonetaryLimits() {
            var dataURL = $('#dataURL').data('url');

            var planId = $('#plans').val();
            var timePeriodId = parseInt($('#time_periods').val());
            var amount = parseFloat($('#Amount').val());

            if (planId == -1) {
                return;
            }
            if (timePeriodId == -1) {
                return;
            }

            $.getJSON(dataURL + "?planId=" + planId + "&timePeriodId=" + timePeriodId, function (data) {
                moneyLimits = $.parseJSON(data.Result).moneyLimits;
                
                var existing = '';
                for (var i = 0; i < moneyLimits.length; i++) {
                    //$('#PlanName').text($("#plans option:selected").text());
                    existing += "<tr id='" + moneyLimits[i].id + "'><td>" + moneyLimits[i].timePeriod + "</td><td>" + moneyLimits[i].amount +
                        "</td><td><input type='checkbox' id='ex_" + moneyLimits[i].id + "' class='ex switch' checked /></td></tr>";
                }
                $('#money_limits tbody').html(existing);

                $('.switch').each(function () {
                    var switchery = new Switchery(this, { color: '#4099ff', jackColor: '#fff' });
                });
            });
        }
        function FormatPlan(data) {
            var options = "";
            for (i = 0; i < data.length; i++)
                options += "<option value='" + data[i].planId + "'>" + data[i].planName + "</option>";
            $('#plans').append(options);
        }
        function FormatTimePeriod(data) {
            var options = "";
            for (i = 0; i < data.length; i++)
                options += "<option value='" + data[i].id + "'>" + data[i].name + "</option>";
            $('#time_periods').append(options);
        }
        function Save() {
            var dataURL = $('#SMTLURL').data('url');

            var planId = $('#plans').val();
            var timePeriodId = parseInt($('#time_periods').val());
            var amount = parseFloat($('#Amount').val());

            if (planId == -1) {
                alert('Select a plan');
                return;
            }
            if (timePeriodId == -1) {
                alert('Select a time period');
                return;
            }
            if (isNaN(amount)) {
                alert('Provide an amount');
                return;
            }

            $.getJSON(dataURL + "?planId=" + planId + "&timePeriodId=" + timePeriodId + "&amount=" + amount, function (data) {
                if (data.Success == true) {
                    data = $.parseJSON(data.Result);
                    console.log(data);

                    if (data.success === true) {
                        NotifySuccess('Operation Complete', 'Request was executed without any recorded errors.');
                    } else {
                        NotifyDanger('Operation Complete', data.message);
                    }
                }
                else {
                    data = $.parseJSON(data.Result);
                    NotifyDanger('Operation Failed', data.message);
                }
                GetTimeMonetaryLimits();
            });
        }
        $('body').on('change', '.switch', function () {
            $elem = $(this);
            $tr = $elem.parent().parent();

            var dataURL = $('#UMTLURL').data('url');
            $.getJSON(dataURL + "?id=" + $tr.prop("id") + "&status=false", function (data) {
                data = $.parseJSON(data.Result);

                if (data.success === true) {
                    NotifySuccess('Operation Complete', 'Request was executed without any recorded errors.');
                    GetTimeMonetaryLimits();
                }
                else {
                    data = $.parseJSON(data.Result);
                    NotifyDanger('Operation Failed', data.message);
                }
            });
        });
    </script>
}