Controllers/ProjectsController.cs
using HyAdmin.AppUtilities;
using HyDirect.Filters;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HyAdmin.Controllers
{
    [MaintenanceFilter]
    [Authorize(Roles = "Admin,MerchantAdmin,Staff")]
    public class ProjectsController : Controller
    {
        // GET: Projects/Index
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ExistingProjects()
        {
            Token t = new Token();
            t = t.GetToken("admin");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.ExistingProjects;

            var client = new RestClient($"{baseURL}{endpoint}");
            var request = new RestRequest(Method.GET);
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("content-type", "application/x-www-form-urlencoded");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            IRestResponse response = client.Execute(request);

            return Json(new { Success = (response.IsSuccessful), Result = response.Content }, JsonRequestBehavior.AllowGet);
        }
        

    }
}

Views/Projects/Index.cshtml
@{
    ViewBag.Title = "Project Management";
}

<!-- Switch component css -->
<link rel="stylesheet" type="text/css" href="~/Content/files/bower_components/switchery/css/switchery.min.css">

<!-- [ breadcrumb ] start -->
<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">
                    <h4 class="m-b-10">Project Management</h4>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="@Url.Action("Index", "Projects")">
                            <i class="feather icon-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Projects</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">View/Setup Projects</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- [ breadcrumb ] end -->

<style>
    .pull-right {
        float: right !important;
    }

    .empty-notification {
        padding: 42px;
        font-weight: lighter;
        font-size: 34px;
    }

    .card .card-block .dropdown-menu > a {
        padding: 4px 7px;
        line-height: 1.429;
    }

    .link-text {
        cursor: pointer;
        font-weight: 600;
        font-size: 12px;
    }

    #category_data tr td {
        padding-bottom: 11px !important;
    }
</style>

<div class="pcoded-inner-content">
    <div class="main-body">
        <div class="page-wrapper">
            <!-- Page-body start -->
            <div class="page-body">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="card recent-operations-card">
                            <div class="card-header">
                                <h5 id="benefit_name">Existing Open Project List</h5>
                            </div>
                            <div class="card-block">
                                <div class="card-scroll">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <table id="existing_projects" class="table table-borderless table-striped">
                                                <tbody id=""></tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="card recent-operations-card">
                            <div class="card-header">
                                <h5 id="benefit_name">Add/Edit Project</h5>
                            </div>
                            <div class="card-block">
                                <div class="row">
                                    <div class="col-sm-12">
                                        Add/Edit projects here
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a id="dataURL" class="hide" data-url="@Url.Action("ExistingProjects", "Projects")"></a>
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "formUrl" }))
    {
        @Html.AntiForgeryToken()
    }
</div>


@section scripts{

    <!-- Switch component js -->
    <script src="~/Content/files/bower_components/switchery/js/switchery.min.js"></script>
    <!-- data-table js -->
    <script src="~/Content/files/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/Content/files/assets/pages/data-table/js/jszip.min.js"></script>
    <script src="~/Content/files/assets/pages/data-table/js/pdfmake.min.js"></script>
    <script src="~/Content/files/assets/pages/data-table/js/vfs_fonts.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Content/files/bower_components/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {

            var dataURL = $('#dataURL').data('url');
            $.getJSON(dataURL, function (data) {
                data = $.parseJSON(data.Result);

                FormatPlan(data.plans);
                FormatTimePeriod(data.timePeriods);
            });
        });
    </script>
}