Controllers/ProductsController.cs
using HyAdmin.AppUtilities;
using HyAdmin.Classes;
using HyAdmin.HDS;
using HyAdmin.Models.ViewModels;
using HyAdmin.Services;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace HyAdmin.Controllers
{
    public class ProductsController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult Setup()
        {
            return View();
        }

        [Authorize]
        public ActionResult Edit()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Payment(int Id, string guid)
        {
            Token t = new Token();
            t = t.GetToken("");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.LocalRetailCustomer;

            var client = new RestClient($"{baseURL}{endpoint}/{Id}/{guid}");
            var request = new RestRequest(Method.GET);
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("content-type", "application/x-www-form-urlencoded");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            request.AddParameter("application/x-www-form-urlencoded", ParameterType.UrlSegment);
            IRestResponse response = client.Execute(request);

            JavaScriptSerializer js = new JavaScriptSerializer();
            dynamic result = js.Deserialize<dynamic>(response.Content);
            RetailCustomerInfo r = new RetailCustomerInfo();
            if (response.IsSuccessful)
            {
                r.Id = Id;
                r.Email = result["email"];
                r.Phone = result["phone"];
                r.Guid = result["guid"];
                r.Date = Convert.ToDateTime(result["dateadded"].ToString()).ToString("dd MMMM, yyyy");
                r.Name = $"{result["lastname"]} {result["firstname"]} {result["othername"]}";
                r.PlanId = Convert.ToInt32(result["planid"]);
                try { r.MemberId = Convert.ToInt32(result["memberid"]); } catch { }

                r.sResponse = result["resp"];
                r.TransferConfirmed = Convert.ToBoolean(result["confirmed"]);
                
                PlanDetails p = new PlanDetails();
                var x = p.GetPlanDefaults(r.PlanId);
                r.PlanName = x.PlanName;
                r.TransactionReference = x.GenerateTxnNo(Id, r.PlanId);
                
                // Amoounts & Convenience
                const double INTERSWITCH_CAPP = 2000;
                const double INTERSWITCH_PERCENTAGE = 0.985;
                r.PlanPrice = ((x.PlanName.ToLower().Contains("family")) ? x.FamilyPrice : x.IndividualPrice);
                r.Amount = r.PlanPrice / INTERSWITCH_PERCENTAGE;
                r.Convenience = r.Amount - r.PlanPrice;
                if (r.Convenience > INTERSWITCH_CAPP)
                    r.Amount = (r.PlanPrice + INTERSWITCH_CAPP);
                r.Convenience = r.Amount - r.PlanPrice;
                
                r.ProductId = OnlinePayment.ProductId;
                r.ItemId = OnlinePayment.PayItemId;
                r.Redirect = OnlinePayment.RedirectURL;
                r.MacKey = OnlinePayment.MacKey;
                r.HashString = $"{r.TransactionReference}{OnlinePayment.ProductId}{OnlinePayment.PayItemId}{Convert.ToDouble(Convert.ToDecimal(r.Amount).ToString("0.##")) * 100}{r.Redirect}{OnlinePayment.MacKey}";

                #region Save Transaction Reference Number
                client = new RestClient($"{baseURL}{APIServices.SaveTransactionReference}/{Id}/{guid}/{r.TransactionReference}");
                request = new RestRequest(Method.POST);
                request.AddHeader("cache-control", "no-cache");
                request.AddHeader("content-type", "application/x-www-form-urlencoded");
                request.AddHeader("authorization", "Bearer " + t.Tokn);
                request.AddParameter("application/x-www-form-urlencoded", ParameterType.UrlSegment);
                response = client.Execute(request); 
                #endregion
            }
            else
            {
                r.Error = "Network connection failed. Please try again later";
                IntelService s = new IntelService();
                s.SendMail("dbello@hygeiahmo.com,aadeyanju@hygeiahmo.com", "Product Purchase Failed", 
                    $"Dear Both,<br /><br />It looks like a network error occured for customer with Id ({Id}).<br />" +
                    $"You may want to engage the customer.<br /><br />Best Regards,", "", "", 1);
            }
            Session["r"] = r;
            return View(r);
        }

        [AllowAnonymous]
        public ActionResult TPayment(int Id, string email)
        {
            ViewBag.Id = Id;
            ViewBag.email = email;
            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Diaspora(int Id)
        {

            ViewBag.Id = Id;
            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public string CO()
        {
            try
            {
                DiasporaOrder d = new DiasporaOrder();
                DiasporaHash Diaspora = d.GetAppsh();
                var client = new RestClient("https://test.diasporapay.net/api.php");
                string parameters = "{\r\n\t\"username\": \"hygieahmo\",\r\n\t\"salt\" : \"" + Diaspora.Salt + "\",\r\n\t\"apiKey\":\"" + Diaspora.Hash + "\",\r\n\t\"command\": \"createOrder\",\r\n\t\"amount\" : \"100\",\r\n\t\"currencyId\" : \"GBP\",\r\n\t\"customerEmail\": \"odm.major@gmail.com\",\r\n\t\"merchantReference\": \"" + Guid.NewGuid().ToString() + "\"\r\n}";
                var request = new RestRequest(Method.POST);
                request.AddHeader("cache-control", "no-cache");
                request.AddParameter("undefined", parameters, ParameterType.RequestBody);
                IRestResponse response = client.Execute(request);
                return response.Content.ToString();
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }

        [HttpPost]
        [AllowAnonymous]
        //[ValidateAntiForgeryToken]
        public string CreateOrder(int retailCustomerId, string __RequestVerificationToken)
        {
            using (var db = new Models.ExistingDBs.HyDirect())
            {
                var retailC = db.RetailCustomers.Find(retailCustomerId);
                if (retailC != null)
                {
                    DiasporaOrder d = new DiasporaOrder();
                    var OrderResponse = d.CreateOrder(Convert.ToInt32(retailCustomerId), retailC.planid, retailC.email);
                    return OrderResponse.Content.ToString();
                }
                return "Retail customer not found";
            }
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult PaymentDetails()
        {
            RetailCustomerInfo r = new RetailCustomerInfo();
            try
            {
                r = (RetailCustomerInfo)Session["r"];
                Session.Abandon();
            }
            catch { r.Error = "Unable to get details. Please check your internet and refresh your browser"; };
            return Json(r, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult AcceptTerms(int Id)
        {
            Token t = new Token();
            t = t.GetToken("");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.AcceptTerms;

            var client = new RestClient($"{baseURL}{endpoint}/{Id}");
            var request = new RestRequest(Method.POST);
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("content-type", "application/x-www-form-urlencoded");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            request.AddParameter("application/x-www-form-urlencoded", ParameterType.UrlSegment);
            IRestResponse response = client.Execute(request);
            return Json((response.IsSuccessful), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult RejectTerms(int Id)
        {
            Token t = new Token();
            t = t.GetToken("");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.RejectTerms;

            var client = new RestClient($"{baseURL}{endpoint}/{Id}");
            var request = new RestRequest(Method.POST);
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("content-type", "application/x-www-form-urlencoded");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            request.AddParameter("application/x-www-form-urlencoded", ParameterType.UrlSegment);
            IRestResponse response = client.Execute(request);
            return Json((response.IsSuccessful), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult UpdatePaymentType(int Id, int PaymentMethod)
        {
            Token t = new Token();
            t = t.GetToken("");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.UpdatePaymentType;

            var client = new RestClient($"{baseURL}{endpoint}/{Id}/{PaymentMethod}");
            var request = new RestRequest(Method.POST);
            request.AddHeader("cache-control", "no-cache");

Views/Products/Diaspora.cshtml
@{
    ViewBag.Title = "Third Party Payment";
    Layout = "~/Views/Shared/_Semi.cshtml";
}
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "formUrl" }))
{
    @Html.AntiForgeryToken()

    <div class="text-center" style="width: 100%; height: 2000px; overflow: hidden; background: #FFF;">

        <style>
            input {
                padding: 15px !important;
            }
        </style>
        <div>
            <h3 style="margin-top: 30px; text-align: center;">One more thing... We need your information</h3>
        </div>
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-offset-4 col-sm-4 text-left">
                <div style="border: 1px solid #ccc; padding: 20px; border-radius: 5px;">

                    <div class="alert alert-info">Complete the form and click proceed to save your data and continue on to the payment instructions on the next page.</div>

                    <div style="border: 1px solid #ccc; padding: 20px; border-radius: 5px;">
                        <label for="name">Buyer Name</label>
                        <input class="form-control" placeholder="Lastname Firstname" id="name" />
                        <br />

                        <label for="email">Buyer Email</label>
                        <input class="form-control" placeholder="someone@email.com" id="email" />
                        <br />

                        <label for="phone">Buyer Phone <span class="text-muted">(Optional)</span></label>
                        <input class="form-control" id="phone" />
                    </div>
                </div>
            </div>
        </div>
        <br />

        <a class="btn btn-danger text-white" onclick="javascript:history.back()"><i class="fa fa-arrow-left"></i>&nbsp;Back to Website</a>
        &nbsp;&nbsp;&nbsp;

        <a class="btn btn-primary text-white proceed" data-href="http://fundgate.ng/hygeiaHmo/@ViewBag.Id/@ViewBag.guid">Proceed&nbsp;<i class="go fa fa-arrow-right"></i></a>
        &nbsp;

        <span id='loading1'>
            <img id='l-i' src='https://online.hygeiahmo.com/hyenrollee/content/images/loading.gif' class='loading hide' style='width:40px;' />
        </span>

        <input type="hidden" class="hide" id="Id" value="@ViewBag.Id" />
        <input type="hidden" class="hide" id="OrderResponse" value="@ViewBag.OrderResponse" />
        <a id="redirect" data-url="@ViewBag.redirect"></a>

        <dov class="hide">
            <a id="order-url" data-url="@Url.Action("CreateOrder", "Products")"></a>
        </dov>
    </div>
}
    @section scripts {
        <script>

            $(function () {

                var form = $('#formUrl');
                var token = $('input[name="__RequestVerificationToken"]', form).val();
             

                $('.proceed').click(function () {
                    Proceed();
                });

                var ValidateEmail       = function (email) {
                    var re = /^(([^<>()\[\]\\.,;:\s@@"]+(\.[^<>()\[\]\\.,;:\s@@"]+)*)|(".+"))@@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
                    return re.test(email);
                }
                var Proceed             = function () {
                    var $name = $('#name');
                    if ($name.val() === '') {
                        alert('Please provide your name.');
                        return false;
                    }
                    var $email = $('#email');
                    if (!ValidateEmail($email.val())) {
                        alert('Please proivide a valid email');
                        return false;
                    }
                    var $phone = $('#phone');

                    var data = {
                        Id: $('#Id').val(),
                        name: $name.val().split(' '),
                        phone: $phone.val(),
                        email: $email.val(),
                    };
                    var settings = {
                        "async": true,
                        "crossDomain": true,
                        "url": "https://online.hygeiahmo.com/hygeiaapiservice/api/RetailCustomers/SaveDiasporaBuyerInfo",
                        "method": "POST",
                        "headers": {
                            "content-type": "application/x-www-form-urlencoded",
                        },
                        "data": {
                            "RetailCustomerId": data.Id,
                            "LastName": data.name[0],
                            "FirstName": data.name[1] || '',
                            "OtherName": data.name[2] || '',
                            "Email": data.email,
                            "Phone": data.phone
                        }
                    }

                    $('.loading').removeClass('hide');
                    jQuery.ajax(settings).done(function (response) {
                        //console.log(response);
                        CreateOrder();
                    });
                }
                var CreateOrder         = function () {
                    var error = function (e) {
                        console.log(e);
                    };
                    var success = function (data) {
                        try { data = window.JSON.parse(data.response); } catch (e) { }
                        d = data.response;
                        if (d.statusType !== 'Failed' && (d.status === 1 || d.status === 0)) {

                            SaveCallBackResult(d);

                        } else {
                            alert('Sorry, we were unable to complete your request at the time. Please retry later.');
                        }
                        
                        $('.loading').addClass('hide');
                    };
                    var data = {
                        retailCustomerId: $('#Id').val(),
                        __RequestVerificationToken: token
                    };
                    
                    $('.loading').removeClass('hide');
                    POSTToServer($("#order-url").data("url"), JSON.stringify(data), success, error);
                }
                var SaveCallBackResult  = function (d) {
                    var settings = {
                        "async": true,
                        "crossDomain": true,
                        "url": "https://online.hygeiahmo.com/hygeiaapiservice/api/RetailCustomers/DiasporaResponse",
                        "method": "POST",
                        "headers": {
                            "content-type": "application/x-www-form-urlencoded",
                        },
                        "data": {
                            "Amount": d.amount,
                            "Status": d.status,
                            "StatusType": d.statusType || "NA",
                            "Expiry": d.expiryDate || "NA",
                            "Id": d.id || "NA",
                            "MerchantReference": d.merchantReference || "NA",
                            "ProviderReference": d.providerReference || "NA"
                        }
                    }
                    jQuery.ajax(settings).done(function (response) {
                        console.log(response);
                        console.log(d.orderRefUrl);
                        location.href = d.orderRefUrl;
                    });
                }
                var POSTToServer        = function (_URL, data, success, error) {
                    $.ajax({
                        type: 'POST',
                        url: _URL,
                        data: data,
                        contentType: 'application/json; charset=utf-8',
                        dataType: 'json',
                        success: success,
                        error: error
                    });
                }

            });
        </script>
    }

Views/Products/TPayment.cshtml
@{
    ViewBag.Title = "Third Party Payment";
    Layout = "~/Views/Shared/_Semi.cshtml";
}

    <div class="text-center" style="width: 100%; height: 2000px; overflow: hidden; background: #FFF;">
        <h3 style="margin-top: 30px;">Third Party Payment</h3>
        <p style="width: 70%; margin: 0px auto;">
            You are being redirected to Fundgate, a licensed lender, to complete your application. Please note that Hygeia HMO has no input in this process and Fundgate solely determines eligibility for credit purposes.
            Hygeia HMO shall not be liable for the decisions of Fundgate and any resulting actions thereafter.
        </p>
        <br />
        <a class="btn btn-danger text-white" onclick="javascript:history.back()"><i class="a fa-left-arrow"></i>Back to Website</a>
        &nbsp;&nbsp;&nbsp;
        <a class="btn btn-primary text-white" href="http://fundgate.ng/hygeiaHmo/@ViewBag.Id/@ViewBag.email"><i class="go fa fa-right-arrow" onclick="alert('Dee')"></i>Proceed</a>

    </div>